// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const assets: {
	"some_image_on_roblox.png": string
	"some_sound_on_roblox.ogg": string
}

export = assets