// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const assets: {
	animations: {
		enemies: {
			"Run.rbxm": string
			"Walk.rbxm": string
		}
	}
}

export = assets